# Generated by debtap
# Maintainer: 
# Contributor: 
pkgname=noderadiotray-bin
pkgver=0.10.8
pkgrel=1
pkgdesc="Radio Tray using Nodejs."
arch=('i686' 'x86_64')
url="https://github.com/eriqjaffe/noderadiotray"
license=('')
groups=('')
depends=('alsa-lib' 'at-spi2-core' 'cairo' 'gtk3' 'gvfs' 'hicolor-icon-theme' 'kde-cli-tools' 'libcups' 'libdrm' 'libnotify' 'libx11' 'libxcb' 'libxcomposite' 'libxdamage' 'libxext' 'libxfixes' 'libxkbcommon' 'libxrandr' 'libxtst' 'mesa' 'nspr' 'nss' 'pango' 'trash-cli' 'xdg-utils')
optdepends=('libgnome-keyring'
            'lsb-release'
            'pulseaudio')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source_x86_64=("https://github.com/eriqjaffe/NodeRadioTray/releases/download/0.10.8/noderadiotray_0.10.8_amd64.deb")
sha512sums_x86_64=('6b940532ffa5523d3b02b683b4529046764538b2f556c92bf5b78b149344137b6c1e3764a66777386e071845d20360f86948d5ec405397cb12b383e211c4047f')

package(){

	# Extract package data
	tar -xI unzstd -f data.tar.zst -C "${pkgdir}"

	install -D -m644 "usr/lib/noderadiotray/LICENSES.chromium.html" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	install -D -m644 "usr/share/doc/noderadiotray/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/COPYRIGHT"

}
